const disasterTypes = {
  banjir: { emoji: '🌊', label: 'Banjir' },
  gempa_bumi: { emoji: '🌍', label: 'Gempa Bumi' },
  tanah_longsor: { emoji: '⛰️', label: 'Tanah Longsor' },
  gunung_berapi: { emoji: '🌋', label: 'Gunung Berapi' },
  tsunami: { emoji: '🌊', label: 'Tsunami' },
  kebakaran: { emoji: '🔥', label: 'Kebakaran' },
  angin_kencang: { emoji: '💨', label: 'Angin Kencang' },
  kekeringan: { emoji: '☀️', label: 'Kekeringan' },
  lainnya: { emoji: '⚠️', label: 'Lainnya' },
};

const statusConfig = {
  aktif: { label: 'Aktif', class: 'bg-primary' },
  siaga: { label: 'Siaga', class: 'bg-warning' },
  terkendali: { label: 'Terdangani', class: 'bg-success' },
  selesai: { label: 'Selesai', class: 'bg-muted' },
};

const severityConfig = {
  ringan: { label: 'Ringan', class: 'bg-success text-white' },
  sedang: { label: 'Sedang', class: 'bg-warning text-white' },
  berat: { label: 'Berat', class: 'bg-orange-500 text-white' },
  kritis: { label: 'Kritis', class: 'bg-destructive text-white' },
};

const warningLevels = {
  hijau: { label: 'Hijau', class: 'bg-green-500' },
  kuning: { label: 'Kuning', class: 'bg-yellow-500' },
  oranye: { label: 'Oranye', class: 'bg-orange-500' },
  merah: { label: 'Merah', class: 'bg-destructive' },
};

const aidTypes = {
  makanan: { emoji: '🍞', label: 'Makanan' },
  air_bersih: { emoji: '💧', label: 'Air Bersih' },
  pakaian: { emoji: '👕', label: 'Pakaian' },
  obat_obatan: { emoji: '💊', label: 'Obat-Obatan' },
  tenda: { emoji: '⛺', label: 'Tenda' },
  selimut: { emoji: '🛏️', label: 'Selimut' },
  perlengkapan_bayi: { emoji: '👶', label: 'Perlengkapan Bayi' },
  lainnya: { emoji: '📦', label: 'Lainnya' },
};

const aidStatusConfig = {
  dibutuhkan: { label: 'Dibutuhkan', class: 'bg-destructive' },
  dalam_perjalanan: { label: 'Dalam Perjalanan', class: 'bg-warning' },
  tiba: { label: 'Tiba', class: 'bg-primary' },
  terdistribusi: { label: 'Terdistribusi', class: 'bg-success' },
};

const centerTypes = {
  posko_utama: { emoji: '🏢', label: 'Posko Utama' },
  tempat_pengungsian: { emoji: '🏠', label: 'Tempat Pengungsian' },
  rumah_sakit_lapangan: { emoji: '🏥', label: 'Rumah Sakit Lapangan' },
  dapur_umum: { emoji: '🍳', label: 'Dapur Umum' },
  gudang_logistik: { emoji: '📦', label: 'Gudang Logistik' },
};

const centerStatusConfig = {
  aktif: { label: 'Aktif', class: 'bg-success' },
  penuh: { label: 'Penuh', class: 'bg-destructive' },
  tidak_aktif: { label: 'Tidak Aktif', class: 'bg-muted' },
};

const documentTypes = {
  laporan_kejadian: { emoji: '📋', label: 'Laporan Kejadian' },
  sk_tanggap_darurat: { emoji: '📜', label: 'SK Tanggap Darurat' },
  rencana_kontijensi: { emoji: '📊', label: 'Rencana Kontijensi' },
  kajian_risiko: { emoji: '📈', label: 'Kajian Risiko' },
  data_korban: { emoji: '📉', label: 'Data Korban' },
  dokumentasi_foto: { emoji: '📷', label: 'Dokumentasi Foto' },
  lainnya: { emoji: '📁', label: 'Lainnya' },
};

const provinces = [
  'Jawa Barat', 'Banten', 'DKI Jakarta', 'Jawa Tengah', 'DI Yogyakarta', 'Jawa Timur'
];

const cities = {
  'Jawa Barat': ['Bandung', 'Bekasi', 'Bogor', 'Depok', 'Sukabumi', 'Cirebon', 'Karawang', 'Bandung Barat', 'Garut', 'Tasikmalaya', 'Cianjur', 'Majalengka', 'Sumedang', 'Subang', 'Purwakarta', 'Indramayu', 'Ciamis', 'Kuningan', 'Pangandaran', 'Banjar'],
  'Banten': ['Tangerang', 'Tangerang Selatan', 'Serang', 'Cilegon', 'Pandeglang', 'Lebak'],
  'DKI Jakarta': ['Jakarta Pusat', 'Jakarta Utara', 'Jakarta Timur', 'Jakarta Selatan', 'Jakarta Barat'],
  'Jawa Tengah': ['Semarang', 'Solo', 'Salatiga', 'Kudus', 'Pekalongan', 'Tegal', 'Magelang', 'Surakarta', 'Klaten', 'Boyolali'],
  'DI Yogyakarta': ['Yogyakarta', 'Sleman', 'Bantul', 'Kulon Progo', 'Gunung Kidul'],
  'Jawa Timur': ['Surabaya', 'Malang', 'Sidoarjo', 'Gresik', 'Kediri', 'Mojokerto', 'Pasuruan', 'Probolinggo', 'Jember', 'Banyuwangi'],
};

export const mockDisasters = [
  {
    id: 'D001',
    title: 'Banjir Bandang di Bandung Selatan',
    disaster_type: 'banjir',
    status: 'aktif',
    severity: 'berat',
    location_name: 'Bandung',
    province: 'Jawa Barat',
    latitude: -6.9175,
    longitude: 107.6191,
    description: 'Banjir bandang melanda wilayah Bandung Selatan akibat curah hujan tinggi. Beberapa desa terendam dengan ketinggian air mencapai 2 meter.',
    affected_people: 5420,
    casualties: 12,
    injured: 34,
    displaced: 1850,
    reported_by: 'Dinas PKP Jawa Barat',
    image_url: 'https://images.unsplash.com/photo-1580674684081-7617fbf3d745?w=800',
    incident_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'D002',
    title: 'Gempa Bumi Magnitudo 5.8',
    disaster_type: 'gempa_bumi',
    status: 'siaga',
    severity: 'sedang',
    location_name: 'Cianjur',
    province: 'Jawa Barat',
    latitude: -6.8217,
    longitude: 107.1454,
    description: 'Gempa bumi dengan magnitudo 5.8 mengguncang wilayah Cianjur dan sekitarnya. getaran terasa hingga Bandung.',
    affected_people: 120000,
    casualties: 0,
    injured: 15,
    displaced: 450,
    reported_by: 'BMKG Bandung',
    image_url: 'https://images.unsplash.com/photo-1569949381669-ecf31ae8e613?w=800',
    incident_date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'D003',
    title: 'Tanah Longsor di Garut',
    disaster_type: 'tanah_longsor',
    status: 'aktif',
    severity: 'kritis',
    location_name: 'Garut',
    province: 'Jawa Barat',
    latitude: -7.2157,
    longitude: 107.8989,
    description: 'Tanah longsor menimbun beberapa rumah di kaki gunung. Tim SAR masih melakukan evakuasi.',
    affected_people: 340,
    casualties: 8,
    injured: 22,
    displaced: 156,
    reported_by: 'Basarnas Bandung',
    image_url: 'https://images.unsplash.com/photo-1547683905-f686c993aae5?w=800',
    incident_date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'D004',
    title: 'Kebakaran Hutan di Cirebon',
    disaster_type: 'kebakaran',
    status: 'terkendali',
    severity: 'sedang',
    location_name: 'Cirebon',
    province: 'Jawa Barat',
    latitude: -6.7320,
    longitude: 108.5521,
    description: 'Kebakaran hutan dan lahan melanda kawasan hutan mangrove di pesisir Cirebon. Petugas masih melakukan pendinginan.',
    affected_people: 2500,
    casualties: 0,
    injured: 5,
    displaced: 0,
    reported_by: 'Dinas LH Cirebon',
    image_url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
    incident_date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'D005',
    title: 'Angin Kencang di Bogor',
    disaster_type: 'angin_kencang',
    status: 'selesai',
    severity: 'ringan',
    location_name: 'Bogor',
    province: 'Jawa Barat',
    latitude: -6.5950,
    longitude: 106.8160,
    description: 'Angin kencang dengan kecepatan 65 km/jam menyebabkan kerusakan ringan di beberapa permukiman.',
    affected_people: 450,
    casualties: 0,
    injured: 3,
    displaced: 25,
    reported_by: 'BPBD Kota Bogor',
    image_url: 'https://images.unsplash.com/photo-1527482797697-8795b05a13fe?w=800',
    incident_date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'D006',
    title: 'Letusan Gunung Tangkuban Perahu',
    disaster_type: 'gunung_berapi',
    status: 'siaga',
    severity: 'sedang',
    location_name: 'Bandung',
    province: 'Jawa Barat',
    latitude: -6.7595,
    longitude: 107.5973,
    description: 'Gunung Tangkuban Perahu mengalami peningkatan aktivitas dengan semburan gas vulkanik.',
    affected_people: 8500,
    casualties: 0,
    injured: 0,
    displaced: 320,
    reported_by: 'PVMBG',
    image_url: 'https://images.unsplash.com/photo-1558628456-4b1b8c5c2d99?w=800',
    incident_date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'D007',
    title: 'Banjir di Bekasi',
    disaster_type: 'banjir',
    status: 'terkendali',
    severity: 'sedang',
    location_name: 'Bekasi',
    province: 'Jawa Barat',
    latitude: -6.2415,
    longitude: 106.9925,
    description: 'Genangan banjir akibat hujan deras semalam. Ketinggian air mencapai 80 cm di beberapa titik.',
    affected_people: 12000,
    casualties: 0,
    injured: 8,
    displaced: 450,
    reported_by: 'BPBD Bekasi',
    image_url: 'https://images.unsplash.com/photo-1547683905-f686c993aae5?w=800',
    incident_date: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'D008',
    title: 'Tsunami Warning di Pandeglang',
    disaster_type: 'tsunami',
    status: 'siaga',
    severity: 'berat',
    location_name: 'Pandeglang',
    province: 'Banten',
    latitude: -6.7500,
    longitude: 105.6000,
    description: 'Peringatan tsunami diterbitkan setelah gempa magnitudo 7.1 di laut. Masyarakat diungsikan ke dataran tinggi.',
    affected_people: 45000,
    casualties: 0,
    injured: 0,
    displaced: 12500,
    reported_by: 'BMKG',
    image_url: 'https://images.unsplash.com/photo-1509717587230-ebb9c4a2c0c4?w=800',
    incident_date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const mockAidReports = [
  {
    id: 'A001',
    disaster_id: 'D001',
    disaster_title: 'Banjir Bandang di Bandung Selatan',
    aid_type: 'makanan',
    quantity: 2500,
    unit: 'paket',
    status: 'terdistribusi',
    source: 'BNPB Jakarta',
    destination: 'Posko Utama Bandung Selatan',
    notes: 'Paket makanan lengkap untuk 3 hari',
  },
  {
    id: 'A002',
    disaster_id: 'D001',
    disaster_title: 'Banjir Bandang di Bandung Selatan',
    aid_type: 'air_bersih',
    quantity: 15000,
    unit: 'liter',
    status: 'tiba',
    source: 'PDAM Bandung',
    destination: 'Posko Utama Bandung Selatan',
    notes: 'Air bersih dalam tangki',
  },
  {
    id: 'A003',
    disaster_id: 'D003',
    disaster_title: 'Tanah Longsor di Garut',
    aid_type: 'tend',
    quantity: 50,
    unit: 'unit',
    status: 'dalam_perjalanan',
    source: 'BNPB Jakarta',
    destination: 'Garut',
    notes: 'Tenda pengungsian emergency',
  },
  {
    id: 'A004',
    disaster_id: 'D002',
    disaster_title: 'Gempa Bumi Magnitudo 5.8',
    aid_type: 'selimut',
    quantity: 500,
    unit: 'lembar',
    status: 'dibutuhkan',
    source: '',
    destination: 'Cianjur',
    notes: 'Kebutuhan mendesak karena suhu turun di malam hari',
  },
  {
    id: 'A005',
    disaster_id: 'D008',
    disaster_title: 'Tsunami Warning di Pandeglang',
    aid_type: 'obat_obatan',
    quantity: 200,
    unit: 'paket',
    status: 'dibutuhkan',
    source: '',
    destination: 'Pandeglang',
    notes: 'Obat-obatan dasar dan P3K',
  },
];

export const mockEvacuationCenters = [
  {
    id: 'E001',
    name: 'Posko Utama BPBD Jawa Barat',
    type: 'posko_utama',
    status: 'aktif',
    location_name: 'Bandung',
    province: 'Jawa Barat',
    latitude: -6.9025,
    longitude: 107.6186,
    capacity: 200,
    current_occupancy: 156,
    contact_person: 'Dr. Ahmad Hidayat',
    contact_phone: '0812-3456-7890',
    related_disaster_id: 'D001',
    available_supplies: ['Makanan 500 paket', 'Air bersih 2000 liter', 'Selimut 100 lembar'],
    notes: 'Posko utama koordinasi seluruh operasi',
  },
  {
    id: 'E002',
    name: 'SDN 1 Sukagalih',
    type: 'tempat_pengungsian',
    status: 'aktif',
    location_name: 'Bandung',
    province: 'Jawa Barat',
    latitude: -6.9100,
    longitude: 107.6100,
    capacity: 150,
    current_occupancy: 142,
    contact_person: 'Ibu Siti Nurhaliza',
    contact_phone: '0813-4567-8901',
    related_disaster_id: 'D001',
    available_supplies: ['Makanan 100 paket', 'Air bersih 500 liter'],
    notes: 'Pengungsian untuk warga RT 03/05',
  },
  {
    id: 'E003',
    name: 'Rumah Sakit Umum Cianjur',
    type: 'rumah_sakit_lapangan',
    status: 'penuh',
    location_name: 'Cianjur',
    province: 'Jawa Barat',
    latitude: -6.8217,
    longitude: 107.1454,
    capacity: 100,
    current_occupancy: 100,
    contact_person: 'Dr. Budi Santoso',
    contact_phone: '0821-5678-9012',
    related_disaster_id: 'D002',
    available_supplies: ['Obat-obatan lengkap', 'Alat medis standar'],
    notes: 'Kapasitas penuh, pasien dirujuk ke Bandung',
  },
  {
    id: 'E004',
    name: 'Gudang Logistik Garut',
    type: 'gudang_logistik',
    status: 'aktif',
    location_name: 'Garut',
    province: 'Jawa Barat',
    latitude: -7.2157,
    longitude: 107.8989,
    capacity: 500,
    current_occupancy: 280,
    contact_person: 'H. Abdullah',
    contact_phone: '0852-6789-0123',
    related_disaster_id: 'D003',
    available_supplies: ['Tenda 30 unit', 'Makanan 300 paket', 'Air bersih 3000 liter'],
    notes: 'Pusat distribusi untuk operasi Garut',
  },
  {
    id: 'E005',
    name: 'Dapur Umum PKS',
    type: 'dapur_umum',
    status: 'aktif',
    location_name: 'Bekasi',
    province: 'Jawa Barat',
    latitude: -6.2415,
    longitude: 106.9925,
    capacity: 50,
    current_occupancy: 35,
    contact_person: 'Pak Rahmat',
    contact_phone: '0814-7890-1234',
    related_disaster_id: 'D007',
    available_supplies: ['Beras 200 kg', 'Lauk pauk 500 porsi', 'Air mineral 100 box'],
    notes: 'Melayani 3 posko pengungsian',
  },
];

export const mockEarlyWarnings = [
  {
    id: 'W001',
    title: 'Peringatan Dini Banjir Jakarta',
    warning_level: 'kuning',
    disaster_type: 'banjir',
    affected_regions: ['Jakarta Utara', 'Jakarta Timur', 'Jakarta Barat'],
    description: 'BMKG memperingatkan potensi banjir di wilayah Jakarta akibat hujan dengan intensitas tinggi.',
    recommendation: 'Masyarakat di daerah rawan banjir diharapkan meningkatkan kewaspadaan dan memantau informasi resmi.',
    source: 'BMKG',
    valid_until: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    is_active: true,
  },
  {
    id: 'W002',
    title: 'Aktivitas Gempa Bumi Meningkat',
    warning_level: 'oranye',
    disaster_type: 'gempa_bumi',
    affected_regions: ['Cianjur', 'Bandung', 'Sukabumi'],
    description: 'Terdeteksi peningkatan aktivitas seismik di zona subduksi. Masyarakat diminta siap siaga.',
    recommendation: 'Siapkan tas darurat, ketahui jalur evakuasi, dan hindari bangunan non-engineering.',
    source: 'PVMBG-BMKG',
    valid_until: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    is_active: true,
  },
  {
    id: 'W003',
    title: 'Letusan Freatik Gunung Tangkuban Perahu',
    warning_level: 'merah',
    disaster_type: 'gunung_berapi',
    affected_regions: ['Bandung', 'Subang', 'West Bandung'],
    description: 'Status ditingkatkan ke Level III (Siaga). Letusan freatik dapat terjadi sewaktu-waktu.',
    recommendation: 'Dilarang beraktivitas dalam radius 1.5 km dari kawah. Siapkan masker dan kacamata.',
    source: 'PVMBG',
    valid_until: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    is_active: true,
  },
  {
    id: 'W004',
    title: 'Peringatan Tsunami',
    warning_level: 'merah',
    disaster_type: 'tsunami',
    affected_regions: ['Pandeglang', 'Lebak', 'Cilegon'],
    description: 'Peringatan tsunami diterbitkan untuk pesisir selatan Banten. Ketinggian gelombang diprediksi 0.5-3 meter.',
    recommendation: 'Segera evakuasi ke dataran tinggi minimal 30 meter di atas permukaan laut.',
    source: 'BMKG',
    valid_until: new Date(Date.now() + 6 * 60 * 60 * 1000).toISOString(),
    is_active: true,
  },
  {
    id: 'W005',
    title: 'Cuaca Ekstrem Jawa Barat',
    warning_level: 'hijau',
    disaster_type: 'angin_kencang',
    affected_regions: ['Bandung', 'Bekasi', 'Bogor', 'Depok'],
    description: 'Sistem tekanan rendah di Laut Jawa menyebabkan hujan disertai angin kencang.',
    recommendation: 'Pastikan struktur bangunan aman dan hindari kegiatan outdoor.',
    source: 'BMKG',
    valid_until: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    is_active: true,
  },
];

export const mockDocuments = [
  {
    id: 'DOC001',
    title: 'Laporan Kejadian Banjir Bandung Januari 2024',
    document_type: 'laporan_kejadian',
    related_disaster: 'D001',
    province: 'Jawa Barat',
    year: 2024,
    file_url: 'https://example.com/doc1.pdf',
    description: 'Laporan lengkap kejadian banjir bandang di Bandung Selatan',
    uploaded_by: 'Dinas PKP Jawa Barat',
  },
  {
    id: 'DOC002',
    title: 'SK Tanggap Darurat Gempa Cianjur',
    document_type: 'sk_tanggap_darurat',
    related_disaster: 'D002',
    province: 'Jawa Barat',
    year: 2024,
    file_url: 'https://example.com/doc2.pdf',
    description: 'Surat Keputusan Kepala BPBD tentang penetapan tanggap darurat',
    uploaded_by: 'BPBD Jawa Barat',
  },
  {
    id: 'DOC003',
    title: 'Rencana Kontijensi Bencana 2024',
    document_type: 'rencana_kontijensi',
    related_disaster: '',
    province: 'Jawa Barat',
    year: 2024,
    file_url: 'https://example.com/doc3.pdf',
    description: 'Dokumen rencana kontijensi tahunan untuk provinsi Jawa Barat',
    uploaded_by: 'BPBD Jawa Barat',
  },
  {
    id: 'DOC004',
    title: 'Kajian Risiko Bencana di Pesisir Banten',
    document_type: 'kajian_risiko',
    related_disaster: '',
    province: 'Banten',
    year: 2023,
    file_url: 'https://example.com/doc4.pdf',
    description: 'Kajian lengkap risiko tsunami di wilayah pesisir Banten',
    uploaded_by: 'BRIN',
  },
  {
    id: 'DOC005',
    title: 'Dokumentasi Foto Banjir Bekasi',
    document_type: 'dokumentasi_foto',
    related_disaster: 'D007',
    province: 'Jawa Barat',
    year: 2024,
    file_url: 'https://example.com/doc5.zip',
    description: 'Koleksi foto dokumentasi kejadian banjir di Bekasi',
    uploaded_by: 'Tim Dokumentasi BPBD',
  },
];

export {
  disasterTypes,
  statusConfig,
  severityConfig,
  warningLevels,
  aidTypes,
  aidStatusConfig,
  centerTypes,
  centerStatusConfig,
  documentTypes,
  provinces,
  cities,
};
